### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by SnowFox102** [NekoNova/WatcherEx#9] opened 2015-04-09 19:47 UTC
Entering the game (or reloading UI) causes the following error:

...s\WatcherEx-master\GeminiSettings\GeminiSettings.lua:91: attempt to call method 'SliderChanged' (a nil value)
stack trace:
	...s\WatcherEx-master\GeminiSettings\GeminiSettings.lua:91: in function 'ApplyToForm'
	...ddons\WatcherEx-master\GeminiFilter\GeminiFilter.lua:1542: in function <...ddons\WatcherEx-master\GeminiFilter\GeminiFilter.lua:1527>
	(tail call): ?
	...CSOFT\WildStar\Addons\WatcherEx-master\WatcherEx.lua:470: in function 'UpdateRulesList'
	...CSOFT\WildStar\Addons\WatcherEx-master\WatcherEx.lua:131: in function <...CSOFT\WildStar\Addons\WatcherEx-master\WatcherEx.lua:108>

**Comment by NekoNova** [comment] 2015-04-09 20:03
Duplicate of previous UI errors.
It's the same issue.

**Closed by NekoNova** 2015-04-09 20:03 UTC
